### ISSUE TITLE
Minor spelling mistakes on admin panel -> new blog page

### ISSUE THREAD

**Issue by King-Mob** [xpert-idea/xipblog#29]
We're developing a site using this blog module for a client (thanks very much for releasing it), and there's some small spelling mistakes that they've noticed.

On the 
`admin panel -> Xpert Blog -> Blog posts -> add new`
page.

`Standrad` instead of `Standard`
`Seperate` instead of `Separate`
`irame` instead of `iframe`
`anudio sourch` instead of (I assume) `an audio source`

Screenshot of first one:
https://user-images.githubusercontent.com/59023121/121229302-acc92100-c885-11eb-83a5-fdae5e2244be.png

Hope this is helpful and thanks again for making the module!

**Comment by xpert-idea** [comment]
Thanks for comments. We will take a look the spelling issues.

**Comment by xpert-idea** [comment]
Please pull the latest one. We have fixed it. Thanks
